[package]
name          = "quantumvault-core"
version       = "0.1.0"
edition       = "2021"
rust-version  = "1.75"
authors       = ["Dhruvil <dhruvil@quantumvault.dev>"]
description   = "Post-quantum cryptography SDK core — hybrid PQC primitives"
license       = "MIT OR Apache-2.0"
repository    = "https://github.com/Dhruvil-8/quantumvault-sdk"
keywords      = ["post-quantum", "cryptography", "ml-kem", "ml-dsa", "pqc"]
categories    = ["cryptography", "no-std"]

[dependencies]
fips203          = "0.4"
fips204          = "0.4"
x25519-dalek     = { workspace = true }
chacha20poly1305 = { workspace = true }
hkdf             = { workspace = true }
sha3             = { workspace = true }
rand             = { workspace = true }
rand_core        = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
bincode          = { workspace = true }
base64           = { workspace = true }
hex              = { workspace = true }
thiserror        = { workspace = true }
zeroize          = { workspace = true }
chrono           = { workspace = true }
blake3           = "1"

[dev-dependencies]
anyhow         = { workspace = true }
criterion      = { version = "0.5", features = ["html_reports"] }

[[bench]]
name    = "crypto"
harness = false
